<?php

//$dates_in is an array with date0 and date1 in Datatime object
//$options is an array with the values to set the date.
function datetime2array($dates_in,$options){
  $modo=$options[0];
  $tipo=$options[1];
  $cantidad=$options[2];
  //obtener fechas
  $date1=$dates_in[0];
  $date2=$dates_in[1];
  
  //Si modo es 1 entonces recoger ambas fechas y convertir a array
  //si modo es 2, entonces hay que calcular la primera fecha, luego convertir a array
  //Entonces, es necesario verificar si es 1, 2 u otro valor
  //Luego tomar las fechas conseguidas y generar el array
  if ($modo == 1){
$segundos=$date1->format('s');
$minutos=$date1->format('i');
$horas=$date1->format('G');
$dia_mes=$date1->format('j');
$dia_semana=$date1->format('w');
$mes=$date1->format('m');
$year=$date1->format('Y');
$dia_año=($date1->format('z'))+1;
$dia_semana_str= $date1->format('l');
$mes_str= $date1->format('F');
$time_stamp_1= $date1->getTimestamp();
    $array_fecha1=array(
            'seconds' => $segundos,
            'minutes' =>  $minutos,
            'hours' =>  $horas,
            'mday' => $dia_mes,
            'wday' =>  $dia_semana,
           'mon' => $mes ,
            'year' =>  $year,
            'yday'=> $dia_año,
            'weekday' => $dia_semana_str,
            'month' =>  $mes_str,
           0 =>$time_stamp_1,
);
$segundos=$date2->format('s');
$minutos=$date2->format('i');
$horas=$date2->format('G');
$dia_mes=$date2->format('j');
$dia_semana=$date2->format('w');
$mes=$date2->format('m');
$year=$date2->format('Y');
$dia_año=($date2->format('z'))+1;
$dia_semana_str= $date2->format('l');
$mes_str= $date2->format('F');
$time_stamp_2= $date2->getTimestamp();
    $array_fecha2=array(
            'seconds' => $segundos,
            'minutes' =>  $minutos,
            'hours' =>  $horas,
            'mday' => $dia_mes,
            'wday' =>  $dia_semana,
           'mon' => $mes ,
            'year' =>  $year,
            'yday'=> $dia_año,
            'weekday' => $dia_semana_str,
            'month' =>  $mes_str,
           0 =>$time_stamp_2,
);
  }
  elseif ($modo == 2){
    $timestamp_fecha2=$date2->getTimestamp();
    $array_fecha2=getdate($timestamp_fecha2);      
    $intervalo=new DateInterval('P'.$cantidad.'D');
    $dias_intervalo=$intervalo->format('%d días');
    $fecha1_obj=$date2;
    $fecha1_obj->sub($intervalo);
//crear date hace un mes
//crear DateTime de hace un mes
    $fecha1_timestamp=$fecha1_obj->getTimestamp();
    $array_fecha1=getdate($fecha1_timestamp);
  }
  else{
    echo "No hay modo de selección para fechas";
  }  
  return array($array_fecha1,$array_fecha2);
  //retornar el arreglo
}